[package]
name = "tantivy-go"
version = "1.0.0"
edition = "2021"
build = "src/build.rs"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.29.2"

[dependencies]
tantivy = { git = "https://github.com/quickwit-oss/tantivy.git", rev = "d8f4c0b703120ed98f06297724dc1522df6019b9" }
cbindgen = "0.29.2"
log = "0.4.29"
env_logger = "0.11.10"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
unicode-segmentation = "1.13.2"
logcall = "0.1.13"
lazy_static = "1.5.0"
phf = { version = "0.11.2", features = ["macros"] }
crunchy = "=0.2.2" #https://github.com/eira-fransham/crunchy/issues/13
base64 = "0.22.1"
